# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/anaconda3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/anaconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jamescouch/dev/cpp/mc-network

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jamescouch/dev/cpp/mc-network

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/anaconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/anaconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jamescouch/dev/cpp/mc-network/CMakeFiles /Users/jamescouch/dev/cpp/mc-network//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jamescouch/dev/cpp/mc-network/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mc-network

# Build rule for target.
mc-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mc-network
.PHONY : mc-network

# fast build rule for target.
mc-network/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/build
.PHONY : mc-network/fast

#=============================================================================
# Target rules for targets named mc_network_demo

# Build rule for target.
mc_network_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mc_network_demo
.PHONY : mc_network_demo

# fast build rule for target.
mc_network_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_network_demo.dir/build.make CMakeFiles/mc_network_demo.dir/build
.PHONY : mc_network_demo/fast

examples/spmv_demo/main.o: examples/spmv_demo/main.cpp.o
.PHONY : examples/spmv_demo/main.o

# target to build an object file
examples/spmv_demo/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_network_demo.dir/build.make CMakeFiles/mc_network_demo.dir/examples/spmv_demo/main.cpp.o
.PHONY : examples/spmv_demo/main.cpp.o

examples/spmv_demo/main.i: examples/spmv_demo/main.cpp.i
.PHONY : examples/spmv_demo/main.i

# target to preprocess a source file
examples/spmv_demo/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_network_demo.dir/build.make CMakeFiles/mc_network_demo.dir/examples/spmv_demo/main.cpp.i
.PHONY : examples/spmv_demo/main.cpp.i

examples/spmv_demo/main.s: examples/spmv_demo/main.cpp.s
.PHONY : examples/spmv_demo/main.s

# target to generate assembly for a file
examples/spmv_demo/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_network_demo.dir/build.make CMakeFiles/mc_network_demo.dir/examples/spmv_demo/main.cpp.s
.PHONY : examples/spmv_demo/main.cpp.s

src/core/csr_matrix.o: src/core/csr_matrix.cpp.o
.PHONY : src/core/csr_matrix.o

# target to build an object file
src/core/csr_matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/src/core/csr_matrix.cpp.o
.PHONY : src/core/csr_matrix.cpp.o

src/core/csr_matrix.i: src/core/csr_matrix.cpp.i
.PHONY : src/core/csr_matrix.i

# target to preprocess a source file
src/core/csr_matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/src/core/csr_matrix.cpp.i
.PHONY : src/core/csr_matrix.cpp.i

src/core/csr_matrix.s: src/core/csr_matrix.cpp.s
.PHONY : src/core/csr_matrix.s

# target to generate assembly for a file
src/core/csr_matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/src/core/csr_matrix.cpp.s
.PHONY : src/core/csr_matrix.cpp.s

src/core/spmv_cpu.o: src/core/spmv_cpu.cpp.o
.PHONY : src/core/spmv_cpu.o

# target to build an object file
src/core/spmv_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/src/core/spmv_cpu.cpp.o
.PHONY : src/core/spmv_cpu.cpp.o

src/core/spmv_cpu.i: src/core/spmv_cpu.cpp.i
.PHONY : src/core/spmv_cpu.i

# target to preprocess a source file
src/core/spmv_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/src/core/spmv_cpu.cpp.i
.PHONY : src/core/spmv_cpu.cpp.i

src/core/spmv_cpu.s: src/core/spmv_cpu.cpp.s
.PHONY : src/core/spmv_cpu.s

# target to generate assembly for a file
src/core/spmv_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/src/core/spmv_cpu.cpp.s
.PHONY : src/core/spmv_cpu.cpp.s

src/gpu/metal/mc_network_metal.o: src/gpu/metal/mc_network_metal.mm.o
.PHONY : src/gpu/metal/mc_network_metal.o

# target to build an object file
src/gpu/metal/mc_network_metal.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc-network.dir/build.make CMakeFiles/mc-network.dir/src/gpu/metal/mc_network_metal.mm.o
.PHONY : src/gpu/metal/mc_network_metal.mm.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mc-network"
	@echo "... mc_network_demo"
	@echo "... examples/spmv_demo/main.o"
	@echo "... examples/spmv_demo/main.i"
	@echo "... examples/spmv_demo/main.s"
	@echo "... src/core/csr_matrix.o"
	@echo "... src/core/csr_matrix.i"
	@echo "... src/core/csr_matrix.s"
	@echo "... src/core/spmv_cpu.o"
	@echo "... src/core/spmv_cpu.i"
	@echo "... src/core/spmv_cpu.s"
	@echo "... src/gpu/metal/mc_network_metal.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

